$(document).ready(function() {
    $(".srzone").click(function() {
        var time = $(".zoneInput").val();
        console.log(time)
        $(".results").append("time");
         $.getJSON('http://timezone' + searchTerm + '&r=json', function(time){
      showResults(time.Search);
    });
    })

});


$(function(){

  $.getJSON('http://www.omdbapi.com/?s=Star%20Wars&r=json', function(time){
    var myData = time.Search;
    $.each(myData, function(index, value){
      console.log(value.Title);
    });
  });
});


[
{"group":"US (Common)",
"zones":[
{"value":"America/Puerto_Rico","name":"Puerto Rico (Atlantic)"},
{"value":"America/New_York","name":"New York (Eastern)"},
{"value":"America/Chicago","name":"Chicago (Central)"},
{"value":"America/Denver","name":"Denver (Mountain)"},
{"value":"America/Phoenix","name":"Phoenix (MST)"},
{"value":"America/Los_Angeles","name":"Los Angeles (Pacific)"},
{"value":"America/Anchorage","name":"Anchorage (Alaska)"},
{"value":"Pacific/Honolulu","name":"Honolulu (Hawaii)"}
]
},
{"group":"America",
"zones":[
{"value":"America/Adak","name":"Adak"},
{"value":"America/Anchorage","name":"Anchorage"},
{"value":"America/Anguilla","name":"Anguilla"},
{"value":"America/Antigua","name":"Antigua"},
{"value":"America/Araguaina","name":"Araguaina"},
{"value":"America/Argentina/Buenos_Aires","name":"Argentina - Buenos Aires"},
{"value":"America/Argentina/Catamarca","name":"Argentina - Catamarca"},
{"value":"America/Argentina/ComodRivadavia","name":"Argentina - ComodRivadavia"},
{"value":"America/Argentina/Cordoba","name":"Argentina - Cordoba"},
{"value":"America/Argentina/Jujuy","name":"Argentina - Jujuy"},
{"value":"America/Argentina/La_Rioja","name":"Argentina - La Rioja"},
{"value":"America/Argentina/Mendoza","name":"Argentina - Mendoza"},
{"value":"America/Argentina/Rio_Gallegos","name":"Argentina - Rio Gallegos"},
{"value":"America/Argentina/Salta","name":"Argentina - Salta"},
{"value":"America/Argentina/San_Juan","name":"Argentina - San Juan"},
{"value":"America/Argentina/San_Luis","name":"Argentina - San Luis"},
{"value":"America/Argentina/Tucuman","name":"Argentina - Tucuman"},
{"value":"America/Argentina/Ushuaia","name":"Argentina - Ushuaia"},
{"value":"America/Aruba","name":"Aruba"},
{"value":"America/Asuncion","name":"Asuncion"},
{"value":"America/Atikokan","name":"Atikokan"},
{"value":"America/Atka","name":"Atka"},
{"value":"America/Bahia","name":"Bahia"},
{"value":"America/Barbados","name":"Barbados"},
{"value":"America/Belem","name":"Belem"},
{"value":"America/Belize","name":"Belize"},
{"value":"America/Blanc-Sablon","name":"Blanc-Sablon"},
{"value":"America/Boa_Vista","name":"Boa Vista"},
{"value":"America/Bogota","name":"Bogota"},
{"value":"America/Boise","name":"Boise"},
{"value":"America/Buenos_Aires","name":"Buenos Aires"},
{"value":"America/Cambridge_Bay","name":"Cambridge Bay"},
{"value":"America/Campo_Grande","name":"Campo Grande"},
{"value":"America/Cancun","name":"Cancun"},
{"value":"America/Caracas","name":"Caracas"},
{"value":"America/Catamarca","name":"Catamarca"},
{"value":"America/Cayenne","name":"Cayenne"},
{"value":"America/Cayman","name":"Cayman"},
{"value":"America/Chicago","name":"Chicago"},
{"value":"America/Chihuahua","name":"Chihuahua"},
{"value":"America/Coral_Harbour","name":"Coral Harbour"},
{"value":"America/Cordoba","name":"Cordoba"},
{"value":"America/Costa_Rica","name":"Costa Rica"},
{"value":"America/Cuiaba","name":"Cuiaba"},
{"value":"America/Curacao","name":"Curacao"},
{"value":"America/Danmarkshavn","name":"Danmarkshavn"},
{"value":"America/Dawson","name":"Dawson"},
{"value":"America/Dawson_Creek","name":"Dawson Creek"},
{"value":"America/Denver","name":"Denver"},
{"value":"America/Detroit","name":"Detroit"},
{"value":"America/Dominica","name":"Dominica"},
{"value":"America/Edmonton","name":"Edmonton"},
{"value":"America/Eirunepe","name":"Eirunepe"},
{"value":"America/El_Salvador","name":"El Salvador"},
{"value":"America/Ensenada","name":"Ensenada"},
{"value":"America/Fortaleza","name":"Fortaleza"},
{"value":"America/Fort_Wayne","name":"Fort Wayne"},
{"value":"America/Glace_Bay","name":"Glace Bay"},
{"value":"America/Godthab","name":"Godthab"},
{"value":"America/Goose_Bay","name":"Goose Bay"},
{"value":"America/Grand_Turk","name":"Grand Turk"},
{"value":"America/Grenada","name":"Grenada"},
{"value":"America/Guadeloupe","name":"Guadeloupe"},
{"value":"America/Guatemala","name":"Guatemala"},
{"value":"America/Guayaquil","name":"Guayaquil"},
{"value":"America/Guyana","name":"Guyana"},
{"value":"America/Halifax","name":"Halifax"},
{"value":"America/Havana","name":"Havana"},
{"value":"America/Hermosillo","name":"Hermosillo"},
{"value":"America/Indiana/Indianapolis","name":"Indiana - Indianapolis"},
{"value":"America/Indiana/Knox","name":"Indiana - Knox"},
{"value":"America/Indiana/Marengo","name":"Indiana - Marengo"},
{"value":"America/Indiana/Petersburg","name":"Indiana - Petersburg"},
{"value":"America/Indiana/Tell_City","name":"Indiana - Tell City"},
{"value":"America/Indiana/Vevay","name":"Indiana - Vevay"},
{"value":"America/Indiana/Vincennes","name":"Indiana - Vincennes"},
{"value":"America/Indiana/Winamac","name":"Indiana - Winamac"},
{"value":"America/Indianapolis","name":"Indianapolis"},
{"value":"America/Inuvik","name":"Inuvik"},
{"value":"America/Iqaluit","name":"Iqaluit"},
{"value":"America/Jamaica","name":"Jamaica"},
{"value":"America/Jujuy","name":"Jujuy"},
{"value":"America/Juneau","name":"Juneau"},
{"value":"America/Kentucky/Louisville","name":"Kentucky - Louisville"},
{"value":"America/Kentucky/Monticello","name":"Kentucky - Monticello"},
{"value":"America/Knox_IN","name":"Knox IN"},
{"value":"America/La_Paz","name":"La Paz"},
{"value":"America/Lima","name":"Lima"},
{"value":"America/Los_Angeles","name":"Los Angeles"},
{"value":"America/Louisville","name":"Louisville"},
{"value":"America/Maceio","name":"Maceio"},
{"value":"America/Managua","name":"Managua"},
{"value":"America/Manaus","name":"Manaus"},
{"value":"America/Marigot","name":"Marigot"},
{"value":"America/Martinique","name":"Martinique"},
{"value":"America/Matamoros","name":"Matamoros"},
{"value":"America/Mazatlan","name":"Mazatlan"},
{"value":"America/Mendoza","name":"Mendoza"},
{"value":"America/Menominee","name":"Menominee"},
{"value":"America/Merida","name":"Merida"},
{"value":"America/Mexico_City","name":"Mexico City"},
{"value":"America/Miquelon","name":"Miquelon"},
{"value":"America/Moncton","name":"Moncton"},
{"value":"America/Monterrey","name":"Monterrey"},
{"value":"America/Montevideo","name":"Montevideo"},
{"value":"America/Montreal","name":"Montreal"},
{"value":"America/Montserrat","name":"Montserrat"},
{"value":"America/Nassau","name":"Nassau"},
{"value":"America/New_York","name":"New York"},
{"value":"America/Nipigon","name":"Nipigon"},
{"value":"America/Nome","name":"Nome"},
{"value":"America/Noronha","name":"Noronha"},
{"value":"America/North_Dakota/Center","name":"North Dakota - Center"},
{"value":"America/North_Dakota/New_Salem","name":"North Dakota - New Salem"},
{"value":"America/Ojinaga","name":"Ojinaga"},
{"value":"America/Panama","name":"Panama"},
{"value":"America/Pangnirtung","name":"Pangnirtung"},
{"value":"America/Paramaribo","name":"Paramaribo"},
{"value":"America/Phoenix","name":"Phoenix"},
{"value":"America/Port-au-Prince","name":"Port-au-Prince"},
{"value":"America/Porto_Acre","name":"Porto Acre"},
{"value":"America/Port_of_Spain","name":"Port of Spain"},
{"value":"America/Porto_Velho","name":"Porto Velho"},
{"value":"America/Puerto_Rico","name":"Puerto Rico"},
{"value":"America/Rainy_River","name":"Rainy River"},
{"value":"America/Rankin_Inlet","name":"Rankin Inlet"},
{"value":"America/Recife","name":"Recife"},
{"value":"America/Regina","name":"Regina"},
{"value":"America/Resolute","name":"Resolute"},
{"value":"America/Rio_Branco","name":"Rio Branco"},
{"value":"America/Rosario","name":"Rosario"},
{"value":"America/Santa_Isabel","name":"Santa Isabel"},
{"value":"America/Santarem","name":"Santarem"},
{"value":"America/Santiago","name":"Santiago"},
{"value":"America/Santo_Domingo","name":"Santo Domingo"},
{"value":"America/Sao_Paulo","name":"Sao Paulo"},
{"value":"America/Scoresbysund","name":"Scoresbysund"},
{"value":"America/Shiprock","name":"Shiprock"},
{"value":"America/St_Barthelemy","name":"St Barthelemy"},
{"value":"America/St_Johns","name":"St Johns"},
{"value":"America/St_Kitts","name":"St Kitts"},
{"value":"America/St_Lucia","name":"St Lucia"},
{"value":"America/St_Thomas","name":"St Thomas"},
{"value":"America/St_Vincent","name":"St Vincent"},
{"value":"America/Swift_Current","name":"Swift Current"},
{"value":"America/Tegucigalpa","name":"Tegucigalpa"},
{"value":"America/Thule","name":"Thule"},
{"value":"America/Thunder_Bay","name":"Thunder Bay"},
{"value":"America/Tijuana","name":"Tijuana"},
{"value":"America/Toronto","name":"Toronto"},
{"value":"America/Tortola","name":"Tortola"},
{"value":"America/Vancouver","name":"Vancouver"},
{"value":"America/Virgin","name":"Virgin"},
{"value":"America/Whitehorse","name":"Whitehorse"},
{"value":"America/Winnipeg","name":"Winnipeg"},
{"value":"America/Yakutat","name":"Yakutat"},
{"value":"America/Yellowknife","name":"Yellowknife"}
]
},